jwt:
  secret: MzI3ZjExYmQzNTU1NmM1MTQ3M2YxODliMzQxMzY2MDg=
  expiration: 3600 # Tiempo en segundos (por ejemplo, 3600 segundos = 1 hora)
  refreshExpiration: 86400 # Tiempo en segundos (por ejemplo, 86400 segundos = 1 día)



spring:
  application:
    name: Movieplay
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/movieplaydb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    password: martin
  sql:
    init:
      mode: always  # Modo de inicialización para crear la base de datos si no existe 
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
        registration:
          google:
            authorization-grant-type: authorization_code
            client-id: 571491722298-g91suheo3kcimlqkcnhs5cjfu3sefub1.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: profile,email
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
