version: '3.8'

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://root:HCwcHiMSQUlotLiEfGGtJLeXVsuslDMU@viaduct.proxy.rlwy.net:58844/railway?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: HCwcHiMSQUlotLiEfGGtJLeXVsuslDMU

volumes:
  mysql_data:
